apiVersion: v1
kind: Service
metadata:
  name: opds-chatapi
spec:
  selector:
    app.kubernetes.io/name: opds-chatapi
  type: NodePort
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 30000

